### ISSUE TITLE
teste ton code

### ISSUE THREAD

**Issue by JeffAbrahamson** [Mokui/code_ML#2]
Exemple :

```
╭╴ (master=) [virt]╶╮
╰ vagrant@ubuntu-xenial:1 $ p bitcoin.py 
Traceback (most recent call last):
  File "bitcoin.py", line 44, in <module>
    main()
  File "bitcoin.py", line 6, in main
    data = pa.read_csv("data/cours_bitcoin.csv",sep=';', encoding='latin-1')
  File "/home/vagrant/venv/lib/python3.5/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/vagrant/venv/lib/python3.5/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vagrant/venv/lib/python3.5/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/vagrant/venv/lib/python3.5/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/vagrant/venv/lib/python3.5/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'data/cours_bitcoin.csv' does not exist: b'data/cours_bitcoin.csv'
╭╴ (master=) [virt]╶╮
╰ 1, vagrant@ubuntu-xenial:1 $

```

**Comment by Mokui** [comment]
Penses à vérifier si tu possèdes bien data/cours_bitcoin.csv
Il est dans le repo normalement
